config/routes.rb
GradingApp::Application.routes.draw do
  resources :users do
    get :autocomplete_student_name, :on => :collection
    member do
      get "view_home"
      get "setup_teachers"
      get "view_students"
      get "view_roster"
      get "manage_students"
      get "manage_activities"
      get "reset_application"
    end
  end
  resources :students
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "static_pages#index"

  match '/help', :to => 'static_pages#help'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete

  match '/delete_student', :to => 'students#delete'
  match '/students/add_student', :to => 'students#add_student'
  match '/students/add_bulk_users_to_db', :to => 'students#add_bulk_users_to_db'

  post '/change_coach', :to => 'activities#change_coach'
  post '/get_activity', :to => 'activities#get_activity'
  post '/add_activities', :to => 'activities#add_activities'
  post '/update_capacities', :to => 'activities#update_capacities'
  post '/confirm_add', :to => 'activities#confirm_add_activities'
  post '/users/add_to_activity', :to => 'activities#add_to_activity'
  post '/load_student_activities', :to => 'activities#load_student_activities'

  match '/users/add_user', :to => 'users#add_user'
  match '/reload_teachers', :to => 'users#reload_teachers'
  match '/reload_students', :to => 'users#reload_students'
  match '/users/update_schedules', :to => 'users#update_schedules'
  match '/reload_schedules', :to => 'users#reload_schedules'
  match '/load_student_roster', :to => 'users#load_roster'
  match '/load_print_view', :to => 'users#print_view'
  match '/get_roster_title', :to => 'users#roster_title'
  match '/search_student', :to => 'users#search_student'
  match '/confirm_password', :to => 'users#confirm_password'
  match '/confirm_reset_application', :to => 'users#confirm_reset_application'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :grade_level, :name, :period, :sign_in_teacher

  validates :name, :presence => true
  validates :period, :presence => true
  validates :grade_level, :presence => true
  validates :sign_in_teacher, :presence => true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def show
		@student = Student.find(params[:id])
	end

	def add_student
		@new_user = Student.new(:name => params[:u_name], :period => params[:u_period], :grade_level => params[:u_grade_level], :sign_in_teacher => params[:u_sign_in_teacher])

		if @new_user.save
			flash[:success] = "Added"
		else
			flash[:failure] = "Failed"
		end
	end
	def add_bulk_users_to_db
		users = params[:users]

		n_user = []
		(users.size).times do |u|
			user = users[u].split(/,/)
			n_user[u] = user
		end

		(n_user.size).times do |n_u|
			@new_user = Student.new(:name => n_user[n_u][0], :period => n_user[n_u][1], :grade_level => n_user[n_u][2], :sign_in_teacher => n_user[n_u][3])
			
			if @new_user.save
				flash[:success] = "Added #{n_u + 1} students"
			else
				flash[:failure] = "Failed"
			end
		end
	end

	def delete
		if Student.find(:first, :conditions => { :name => params[:student] }).destroy
			render :text => "Student deleted!"
		else
			render :text => "Student was not deleted!"
		end
	end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_add_student_form.html.erb
<%= form_tag("/students/add_student", :id => "add_user_form") do %>
<div class="tabular_opp">
	<table>
		<tbody>
			<tr>
				<td class="left-side"><span class="det">name:</span></td>
				<td><%= text_field_tag 'u_name' %></td>
				<td class="left-side"><span class="det">sign in teacher:</span></td>
				<td><%= text_field_tag 'u_sign_in_teacher' %></td>
			</tr>
			<tr>
				<td class="left-side"><span class="det">period:</span></td>
				<td><%= text_field_tag 'u_period' %></td>
				<td class="left-side"><span class="det">grade level:</span></td>
				<td><%= text_field_tag 'u_grade_level' %></td>
			</tr>
			<tr>
				<td></td>
				<td>
					<%= submit_tag 'add student', :class => 'btn btn-primary' %>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<% end %>

app/views/students/_list_activities.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$.post('/load_student_activities', { name: $('table thead tr th h4').text(), marking: "1" }, function(r) { $('.list_activities table tbody tr').html(r); });
		$('#select_marking_period').change(function() {
			$.post('/load_student_activities', { name: $('table thead tr th h4').text(), marking: $(this).val() }, function(r) { $('.list_activities table tbody tr').html(r); });
		});
	})
</script>
<div class="list_activities">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Activity 1</th>
				<th>Activity 2</th>
				<th>Activity 3</th>
			</tr>
		</thead>
		<tbody>
			<tr></tr>
		</tbody>
	</table>
</div>
<style type="text/css">
	select {
		margin-top:5px;
	}
</style>

app/views/students/_student.html.erb
<% if over %>
	<% @student_results.each do |s| %>
		<tr id="<%= s.id %>">
			<td class="s_name"><%= link_to s.name, student_path(s) %></td>
			<td class="s_period"><%= s.period %></td>
			<td class="s_grade_level"><%= s.grade_level %></td>
		</tr>
	<% end %>
<% else %>
	<% if view %>
		<% @student_results.each do |s| %>
			<tr id="<%= s.id %>">
				<td class="s_name"><%= link_to s.name, student_path(s) %></td>
				<td class="s_period"><%= s.period %></td>
				<td class="s_grade_level"><%= s.grade_level %></td>
				<td class="s_sign_in_teacher"><%= s.sign_in_teacher %></td>
				<% if !@user.teacher? %> <td class="s_remove"><%= link_to 'x student', '#', :id => "#{s.name}", :class => "student_delete_link" %></td> <% end %>
			</tr>
		<% end %>
		<script type="text/javascript>">
			$(document).ready(function() {
				$('.student_delete_link').click(function() {
					var id = $(this).prop('id');
					if(confirm("Are you sure you want to delete " + id + "?"))
						$.post('/delete_student', { student: id }, function(r) { alert(r); });
					return false;
				});
			})
		</script>
	<% else %>
		<% @students.each do |s| %>
			<% continue = true %>
			<% students_xml.search("//student").each do |sx| %>
				<% if sx.search("name").inner_text == s.name %>
					<% activity = Activity.find(:first, :conditions => { :name => sx.search("activity").inner_text, :marking_period => mp, :activity_number => act }) %>
					<% if !activity.nil? %>
						<% continue = false %>
					<% end %>
				<% end %>
			<% end %>
			<% if continue %>
				<% if s.period.to_s == per.to_s %>
					<div class="draggable"><span><%= "#{s.name}" %></span></div>
				<% end %>
			<% end %>
		<% end %>
		<script type="text/javascript">
			$(document).ready(function() {
				$('.draggable').click(function(event) {
					$(this).toggleClass('grouped');
				});
				$('.draggable').draggable({
					start: function(event, ui) {
						count = 0;
						if($(this).hasClass('grouped')) {
							collectedData = "<div id='grouped-drags' style='display:none;'>";
							$('.grouped').each(function() {
								count++;
								collectedData += $(this).html();
							});
							collectedData += "</div>";

							prevData = $(this).html();
							$(this).html(count + " " + collectedData);

							prevDropHeight = $('li.droppable').height();
							$('li.droppable').animate({ height: '50px' }, 300);
							$('li.droppable').append("<div class='drag-here'><em>drag here</em></div>");
							prevWidth = $(this).width();
							$(this).css({ width: '15px' });

							$(this).addClass('selected');
						}
						prevPos = $(this).offset();
					},
					stop: function(event, ui) {
						if($(this).hasClass('grouped')) {
							$(this).html(prevData);

							$(this).css({ width: prevWidth });
							$('li.droppable').animate({ height: prevDropHeight }, 300);

							$('li.droppable').children('.drag-here').remove();
							$(this).removeClass('selected');
						}
						$(this).offset({ top: prevPos.top, left: prevPos.left });
					}
				});
				$('.droppable').droppable({
					drop: function(event, ui) {
						$.ajaxSetup({async:false});
						var draggable = ui.draggable;
						if(draggable.hasClass('grouped')) {
							var str = "";
							var act = "";
							var st = new Array();
							$.post('/get_activity', { coach: $(this).prop('id'), act: sec.substring(sec.length - 1, sec.length), mp: prim.substring(prim.length - 1, prim.length) }, function(r) { str = "The following students will be added to <strong>"+ r +"</strong>:\n";act = r; });
							draggable.children('#grouped-drags').children('span').each(function() {
								st.push($(this).html());
								str += $(this).html() + "\n";
							});
							str += "\nIs this correct?";

							if(confirm(str)) {
								//ADD STUDENTS TO ACTIVITY
								$.post('add_to_activity', { students: st, coach: $(this).prop('id'), activity: act, marking: prim.substring(prim.length - 1, prim.length), act_num: sec.substring(sec.length - 1, sec.length), period: $('#period-select').val() }, function(r) { alert(r); });
								change_students();
							}
						}
						$.ajaxSetup({async:true});
					}
				});
			})
		</script>
	<% end %>
<% end %>

app/views/students/_student_side.html.erb
<tbody>
	<tr>
		<td>Grade:</td>
		<td><%= @student.grade_level %></td>
	</tr>
	<tr>
		<td>Period:</td>
		<td><%= @student.period %></td>
	</tr>
	<tr>
		<td>Teacher:</td>
		<td><%= @student.sign_in_teacher %></td>
	</tr>
</tbody>

app/views/students/add_bulk_users_to_db.html.erb
return to <%= link_to 'profile', user_path(current_user) %>

app/views/students/add_student.html.erb
return to <%= link_to 'profile', user_path(current_user) %>

app/views/students/show.html.erb
<% provide(:title, @student.name) %>
<div class="col pull-left">
	<table class="table table-striped">
		<thead>
			<tr>
				<th></th>
				<th><h4><%= @student.name %></h4></th>
			</tr>
		</thead>
		<%= render 'student_side' %>
	</table>
</div>
<div id="main-user-content" class="pull-right">
	<h3>Activities &bull;
		<%= select_tag "select_marking_period", "<option>Select Marking Period...</option><option disabled></option><option value='1' selected>1</option><option value='2'>2</option><option value='3'>3</option><option value='4'>4</option>".html_safe %>
	</h3>
	<%= render :partial => 'list_activities' %>
</div>