config/routes.rb
GradingApp::Application.routes.draw do
  resources :users do
    get :autocomplete_student_name, :on => :collection
    member do
      get "view_home"
      get "setup_teachers"
      get "view_students"
      get "view_roster"
      get "manage_students"
      get "manage_activities"
      get "reset_application"
    end
  end
  resources :students
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "static_pages#index"

  match '/help', :to => 'static_pages#help'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete

  match '/delete_student', :to => 'students#delete'
  match '/students/add_student', :to => 'students#add_student'
  match '/students/add_bulk_users_to_db', :to => 'students#add_bulk_users_to_db'

  post '/change_coach', :to => 'activities#change_coach'
  post '/get_activity', :to => 'activities#get_activity'
  post '/add_activities', :to => 'activities#add_activities'
  post '/update_capacities', :to => 'activities#update_capacities'
  post '/confirm_add', :to => 'activities#confirm_add_activities'
  post '/users/add_to_activity', :to => 'activities#add_to_activity'
  post '/load_student_activities', :to => 'activities#load_student_activities'

  match '/users/add_user', :to => 'users#add_user'
  match '/reload_teachers', :to => 'users#reload_teachers'
  match '/reload_students', :to => 'users#reload_students'
  match '/users/update_schedules', :to => 'users#update_schedules'
  match '/reload_schedules', :to => 'users#reload_schedules'
  match '/load_student_roster', :to => 'users#load_roster'
  match '/load_print_view', :to => 'users#print_view'
  match '/get_roster_title', :to => 'users#roster_title'
  match '/search_student', :to => 'users#search_student'
  match '/confirm_password', :to => 'users#confirm_password'
  match '/confirm_reset_application', :to => 'users#confirm_reset_application'

end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>Physical Education Scheduling/Grading by <a href="mailto:kolbobby@gmail.com">Bobby Koller</a></small>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Phys. Ed.", root_path, :class => 'brand' %>
			<div class="nav-collapse collapse">
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li>
					<% if signed_in? %>
						<%= link_to "Sign out", signout_path, :method => "delete" %>
					<% else %>
						<%= link_to "Sign in", signin_path %>
					<% end %>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!-- [if ly IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/navigation' %>
		<div class="hero-unit">
			<div class="container">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, :class => "alert alert-#{key}") %>
				<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</body>
</html>